[package]
name = "key_gen"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin = "0.19.1"
bitcoin_support  = { path = "../bitcoin_support" }
ethereum_support = { path = "../ethereum_support" }
hex = "0.4"
secp_wrapper = { path = "../secp_wrapper" }
tiny-keccak = "1.5.0"
