rules:
  github-worklows:
    description: "GitHub workflow files must match provided schema"
    message: "{{error}}"
    recommended: true
    severity: error
    given: "$"
    then:
      function: schema
      functionOptions:
        schema:
          $ref: http://json.schemastore.org/github-workflow
