language: minimal
cache:
  yarn: true
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
  - "$TRAVIS_BUILD_DIR/api_tests/node_modules"
sudo: required
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
      key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    - sourceline: 'deb https://deb.nodesource.com/node_10.x/ trusty main'
      key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
    - libzmq3-dev
    - yarn
    - nodejs=10.*
  homebrew:
    packages:
    - yarn
    - zmq
services: docker
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(< rust-toolchain) && source $HOME/.cargo/env
  - which cargo-make || cargo install --debug cargo-make
  # The OSX image of Travis uses nvm instead of homebrew for managing node version
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      nvm install node 10;
      nvm use node 10;
    fi
script: cargo make travis
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-bots
    on_success: never
    on_failure: always
    on_pull_requests: true

