[workspace]

members = [
    "application/bitcoin_htlc",
    "application/bitcoin_wallet",
    "application/common_types",
    "application/ethereum_htlc",
    "application/ethereum_wallet",
    "application/exchange_service",
    "application/fake_treasury_service",
    "application/logging",
    "application/trading_client",
    "application/trading_service",
    "vendor/bitcoin_rpc",
    "vendor/bitcoin_rpc_test_helpers",
    "vendor/bitcoin_support",
    "vendor/ethereum_support",
    "vendor/ganache_rust_web3",
    "vendor/jsonrpc",
    "vendor/key_gen",
    "vendor/lightning_rpc",
    "vendor/trufflesuite_ganachecli",
    "vendor/coblox_bitcoincore",
    "vendor/testcontainers_rs",
    "vendor/event_store",
    "vendor/noise_codec"
]
