[workspace]

members = [
    "bitcoin_htlc",
    "jsonrpc",
    "trading_service",
    "exchange_service",
    "trading_client",
    "fake_treasury_service",
    "common_types",
    "bitcoin_rpc",
    "bitcoin_wallet",
    "bitcoin_support",
    "ethereum_htlc",
    "ganache_rust_web3",
    "ethereum_wallet",
    "key_gen",
    "ganache_node",
    "bitcoin_node",
    "testcontainers_rs",
]
