[package]
name = "digest-macro-derive"
version = "0.1.0"
authors = ["CoBloX <hello@coblox.tech>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
hex = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
