[rpc]
disable = false
interface = "all"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
reseal_min_period = 1000
reseal_max_period = 5000
gas_floor_target = "0x165A0BC00"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 16384
usd_per_tx = "0"
force_sealing= true

[misc]
logging = "own_tx=trace,sync=debug,rpc=trace,mining=trace"
color = true
unsafe_expose = true

[ipc]
disable = true
