[package]
name = "bitcoin_witness"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin_support = { path = "../bitcoin_support" }
failure = "0.1"
secp256k1_support = { path = "../secp256k1_support" }

[dev-dependencies]
bitcoin_rpc_test_helpers = { path = "../bitcoin_rpc_test_helpers" }
bitcoincore-rpc = "0.7"
env_logger = "0.6"
hex = "0.3"
spectral = "0.6"
tc_bitcoincore_client = { path = "../tc_bitcoincore_client" }
testcontainers = "0.7"
