[package]
name = "comit"
version = "0.1.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"
description = "Core functionality of the COMIT protocol"

[dependencies]
bitcoin_support = { path = "../internal/bitcoin_support" }
bitcoin_witness = { path = "../internal/bitcoin_witness" }
blockchain_contracts = { path = "../blockchain_contracts" }
derivative = "1.0.3"
either = "1.5"
ethereum_support = { path = "../internal/ethereum_support" }
futures = "0.1"
hex = "0.3"
libp2p-core = "0.12" # bad
log = "0.4"
rust-crypto = "0.2"
secp256k1_keypair = { path = "../internal/secp256k1_keypair" }
serde = { version = "1", features = ["derive"] } # bad
serde_json = "1" # bad
state_machine_future = { version = "0.2" }
strum = "0.15"
strum_macros = "0.15"
tokio = "0.1" # bad
uuid = { version = "0.7", features = ["serde", "v4"] }

[dev-dependencies]
quickcheck = "0.9.0"
quickcheck_macros = "0.8.0"
spectral = "0.6"
