[package]
name = "ganache_rust_web3"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
web3 = "0.3.0"
serde_derive = "1.0.63"
serde = "1.0.64"
serde_json = "1.0.19"

[dev-dependencies]
ganache_node = { path = "../ganache_node" }