[package]
name = "bam"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bytes = "0.4"
debug_stub_derive = "0.3"
futures = "0.1"
log = "0.4"
memsocket = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "0.1"
tokio-codec = "0.1"

[dev-dependencies]
pretty_env_logger = "0.3"
spectral = "0.6"
