[package]
authors = ["CoBloX developers <team@coblox.tech>"]
name = "cnd"
version = "0.3.0"
edition = "2018"
description = "Reference implementation of a COMIT network daemon."

[dependencies]
anyhow = "1"
binary_macros = "0.6"
bitcoin = "0.19.1"
blockchain_contracts = "0.1"
btsieve = { version = "0.1.0", path = "../btsieve" }
chrono = { version = "0.4", features = ["serde"] }
config = { version = "0.9", features = ["toml"] }
debug_stub_derive = "0.3"
derivative = "1"
derive_more = "0.99.2"
diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = "1.4.0"
directories = "2.0"
either = "1.5"
enum-display-derive = "0.1"
ethereum_support = { path = "../internal/ethereum_support" }
fern = { version = "0.5", features = ["colored"] }
futures = { version = "0.1" }
futures-core = { version = "=0.3.0-alpha.19", features = ["alloc", "compat", "async-await"], package = "futures-preview" }
hex = "0.4"
hex-serde = "0.1.0"
http = "0.1"
http-api-problem = "0.13"
hyper = "0.12"
lazy_static = "1"
libp2p = { version = "0.12" }
libp2p-comit = { path = "../libp2p-comit" }
libsqlite3-sys = { version = ">=0.8.0, <0.13.0", features = ["bundled"] }
log = { version = "0.4", features = ["serde"] }
maplit = "1"
mime = "0.3"
mime_guess = "2.0"
paste = "0.1"
pem = "0.7"
rand = "0.7"
reqwest = { version = "0.9", default-features = false }
rlp = "0.4"
rust-crypto = "0.2"
rustic_hal = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
siren = { version = "0.1", package = "siren-types" }
state_machine_future = { version = "0.2" }
structopt = "0.3"
strum = "0.16"
strum_macros = "0.16"
thiserror = "1"
tokio = "0.1"
toml = "0.5"
url_serde = "0.2.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
void = "1.0.2"
warp = { version = "0.1", default-features = false }

[dev-dependencies]
base64 = "0.11"
bitcoincore-rpc = "0.8.0-rc1"
maplit = "1"
matches = "0.1.8"
memsocket = "0.1"
pretty_env_logger = "0.3"
quickcheck = "0.9.0"
regex = "1.3.1"
serde_urlencoded = "0.6"
spectral = "0.6"
tempfile = "3.1.0"
