[package]
name = "fake-treasury-service"
version = "0.1.0"

authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
serde = "1.0.51"
serde_json = "1.0.17"
serde_derive = "1.0.51"
rocket_contrib = "0.3.10"
