# This should not be used in production
[ethereum]
private_key="3f92cbc79aa7e29c7c5f3525749fd7d90aa21938de096f1b78710befe6d8ef59"

[bitcoin]
mnemonic_key_phrase="crop cash unable insane eight faith inflict route frame loud box vibrant"

[swap]
eth_refund_address="0x147ba99ef89c152f8004e91999fee87bda6cbc3e"
