[package]
name = "ethereum_support"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bigdecimal = "0.1.0"
byteorder = "1.3"
extern_web3 = { package = "web3", version = "0.6" }
lazy_static = "1"
num = "0.2"
regex = "1.2"
rlp = "0.3"
secp256k1_support = { path = "../secp256k1_support" }
serde = { version = "1", features = ["derive"] }
strum = "0.15"
strum_macros = "0.15"
tiny-keccak = "1.5"

[dev-dependencies]
hex = "0.3"
serde_json = "1"
spectral = "0.6"
